[package]
name = "website_checker"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
reqwest = { version = "0.11", features = ["blocking"] }
serde_json = "1.0"
num_cpus = "1.13"

[dev-dependencies]
assert_cmd = "2.0"
tempfile = "3.5"